module.exports = {
  create_user_info_ok: {
    id: 123,
    nick: 'movidas123',
    game_nick: 'el-mejoh',
    asdfg: 'lololo'
  },
  create_user_info_ko: {
    nick: 'other useless nick',
  },
  update_game_nick_user: {
    id: 124,
    nick: 'nick124',
    game_nick: 'nick124',
  },
  update_game_nick: 'nick421',
  update_nick_user: {
    id: 125,
    nick: 'nick125',
    game_nick: 'nick125',
  },
  update_nick: 'nick521',
  update_desired_size: {
    id: 126,
    desired_group_size: 7,
  },
  test_desired_size: 3,
  update_desired_frequency: {
    id: 127,
    desired_interaction_frequency: 3,
  },
  test_desired_frequency: 4,
  valid_user: {
    id: 123,
    nick: 'some nick',
    game_nick: 'some other cool nick',
    desired_group_size: 6,
    desired_interaction_frequency: 1,
    frequency_rating: 5,
    frequency_retings: [],
    friendly_rating: 5,
    friendly_ratings: [],
    created: Date.now(),
    updated: Date.now(),
  },
  wrong_user_1: {
    id: 123,
    nick: '',
    game_nick: 'some other cool nick',
    desired_group_size: 6,
    desired_interaction_frequency: 1,
    frequency_rating: 5,
    frequency_retings: [],
    friendly_rating: 5,
    friendly_ratings: [],
    created: Date.now(),
    updated: Date.now(),
  },
  wrong_user_2: {
    id: 123,
    nick: 'some cool nick',
    game_nick: '',
    desired_group_size: 6,
    desired_interaction_frequency: 1,
    frequency_rating: 5,
    frequency_retings: [],
    friendly_rating: 5,
    friendly_ratings: [],
    created: Date.now(),
    updated: Date.now(),
  },
}